channels:
    - conda-forge

dependencies:
    - conda-forge::pandas==1.3.5
    - conda-forge::numpy==1.24.2
    - conda-forge::plotly==5.9.0
    - conda-forge::pyyaml==6.0
    - pip:
          - streamlit==1.18.1
