name: ditto-env

channels:
    - conda-forge
    - anaconda

dependencies:
    - conda-forge::streamlit==1.18.1
    - anaconda::pandas==1.5.3
    - conda-forge::numpy==1.24.2
    - conda-forge::plotly==5.13.0
    - conda-forge::pyyaml==6.0
