raw_cols:
 - transcript
 - gene
 - consequence
 - protein_hgvs
 - cdna_hgvs
 - chrom
 - pos
 - ref_base
 - alt_base
 - coding
 - aloft.tolerant
 - aloft.recessive
 - aloft.dominant
 - aloft.pred
 - aloft.conf
 - cadd.phred
 - cgd.inheritance
 - chasmplus.score
 - chasmplus.pval
 - civic.molecular_profile_score
 - cosmic.variant_count
 - cosmic_gene.occurrences
 - cscape.score
 - cgc.class
 - cgc.inheritance
 - cancer_genome_interpreter.resistant
 - cancer_genome_interpreter.responsive
 - cancer_genome_interpreter.other
 - ccre_screen._group
 - ccre_screen.bound
 - clingen.disease
 - clingen.classification
 - clinpred.score
 - clinvar.sig
 - clinvar.id
 - clinvar.rev_stat
 - clinvar.sig_conf
 - dann.score
 - dann_coding.dann_coding_score
 - dgi.interaction
 - dgi.score
 - ensembl_regulatory_build.region
 - ess_gene.indispensability_score
 - exac_gene.exac_pli
 - exac_gene.exac_pnull
 - exac_gene.exac_del_score
 - exac_gene.exac_dup_score
 - exac_gene.exac_cnv_score
 - exac_gene.exac_cnv_flag
 - fathmm.fathmm_score
 - fathmm_xf_coding.fathmm_xf_coding_score
 - funseq2.score
 - gerp.gerp_rs
 - ghis.ghis
 - gtex.gtex_tissue
 - gwas_catalog.pval
 - genehancer.feature_name
 - genehancer.score
 - linsight.value
 - lrt.lrt_score
 - lrt.lrt_omega
 - loftool.loftool_score
 - mavedb.score
 - metalr.score
 - metasvm.score
 - mutpred1.mutpred_general_score
 - mutpred_indel.score
 - mutation_assessor.score
 - mutationtaster.score
 - mutationtaster.prediction
 - mutationtaster.model
 - ncbigene.entrez
 - ndex_chd.numhit
 - ndex.numhit
 - ndex_signor.numhit
 - omim.omim_id
 - prec.prec
 - prec.stat
 - provean.score
 - pangalodb.sensitivity
 - pangalodb.specificity
 - phdsnpg.score
 - phastcons.phastcons100_vert
 - phastcons.phastcons470_mamm
 - phastcons.phastcons17way_primate
 - phylop.phylop100_vert
 - phylop.phylop470_mamm
 - phylop.phylop17_primate
 - polyphen2.hdiv_rank
 - polyphen2.hvar_rank
 - revel.score
 - rvis.rvis_evs
 - repeat.repeatclass
 - sift.score
 - sift.med
 - sift.confidence
 - sift.seqs
 - segway.mean_score
 - siphy.logodds_rank
 - spliceai.ds_ag
 - spliceai.ds_al
 - spliceai.ds_dg
 - spliceai.ds_dl
 - spliceai.dp_ag
 - spliceai.dp_al
 - spliceai.dp_dg
 - spliceai.dp_dl
 - uniprot.acc
 - varity_r.varity_r_loo
 - varity_r.varity_er_loo
 - vest.score
 - dbsnp.rsid
 - dbscsnv.ada_score
 - dbscsnv.rf_score
 - gnomad.af
 - gnomad_gene.oe_lof
 - gnomad_gene.oe_mis
 - gnomad_gene.oe_syn
 - gnomad_gene.lof_z
 - gnomad_gene.mis_z
 - gnomad_gene.syn_z
 - gnomad_gene.pLI
 - gnomad_gene.pRec
 - gnomad_gene.pNull
 - gnomad3.af
 - phi.phi

train_cols:
 - transcript
 - gene
 - consequence
 - protein_hgvs
 - cdna_hgvs
 - chrom
 - pos
 - ref_base
 - alt_base
 - clingen.disease
 - clingen.classification
 - ncbigene.entrez
 - omim.omim_id
 - uniprot.acc
 - dbsnp.rsid

display_cols:
  cons:
   - gerp
   - polyphen2
  AF:
   - gnomad
   - gnomad3
  pred:
   - cadd
   - spliceai
   - clinpred
   - revel
   - varity_r
  clinical:
   - clinvar
   - clingen
   - cgd
   - mavedb

id_cols:
 - transcript
 - gene
 - consequence
 - protein_hgvs
 - cdna_hgvs
 - chrom
 - pos
 - ref_base
 - alt_base
 - clingen.disease
 - clingen.classification
 - clinvar.id
 - clinvar.sig
 - clinvar.rev_stat
 - clinvar.sig_conf
 - ncbigene.entrez
 - omim.omim_id
 - uniprot.acc
 - dbsnp.rsid

train_ClinicalSignificance:
 - Uncertain_significance
 - Pathogenic
 - Likely_pathogenic
 - Benign
 - Likely_benign
 - Benign/Likely_benign
 - Pathogenic/Likely_pathogenic
 - Conflicting_interpretations_of_pathogenicity

BenchmarkSignificance:
 - Pathogenic
 - Likely_pathogenic
 - Likely_benign
 - Benign
 - Benign/Likely_benign
 - Pathogenic/Likely_pathogenic
 - Pathogenic,_other
 - Pathogenic/Likely_pathogenic,_other
 - Pathogenic,_drug_response

CLNREVSTAT: #https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/
  -  practice_guideline
  -  reviewed_by_expert_panel
  -  criteria_provided,_multiple_submitters,_no_conflicts

dummies_sep:
 gtex.gtex_tissue: '|'
 dgi.interaction: ','
 cgd.inheritance: '/'
 so: ','
 repeat.repeatclass: ','
 genehancer.feature_name: '/'
 cgc.inheritance: '/'
 cgc.class: ', '

median_scores:
 aloft.tolerant: 0.03175
 aloft.recessive: 0.5456
 aloft.dominant: 0.38385
 cadd.phred: 9.129
 chasmplus.score: 0.073
 chasmplus.pval: 0.277
 civic.molecular_profile_score: 7.5
 cosmic.variant_count: 1.0
 cosmic_gene.occurrences: 1725.0
 cscape.score: 0.436793
 cancer_genome_interpreter.resistant: 0.0
 cancer_genome_interpreter.responsive: 2.0
 cancer_genome_interpreter.other: 0.0
 clinpred.score: 0.109
 dann.score: 0.6540942459117577
 dann_coding.dann_coding_score: 0.994319113925808
 dgi.score: 3.55
 ess_gene.indispensability_score: 0.863945523287189
 exac_gene.exac_pli: 0.0614137585139882
 exac_gene.exac_pnull: 1.01047322872054e-05
 exac_gene.exac_del_score: 0.2455437788049
 exac_gene.exac_dup_score: 0.194157677715669
 exac_gene.exac_cnv_score: 0.034861123316654
 fathmm.fathmm_score: -1.59
 fathmm_xf_coding.fathmm_xf_coding_score: 0.346275
 funseq2.score: 0.498146534129084
 gerp.gerp_rs: 4.66
 ghis.ghis: 0.561316286
 gwas_catalog.pval: 2e-09
 genehancer.score: 1.09
 linsight.value: 0.142985
 lrt.lrt_score: 4.2e-05
 lrt.lrt_omega: 0.099477
 loftool.loftool_score: 0.101
 mavedb.score: 0.8677136380949829
 metalr.score: 0.4031
 metasvm.score: -0.3355
 mutpred1.mutpred_general_score: 0.7979999999999999
 mutpred_indel.score: 0.581
 mutation_assessor.score: 2.0
 mutationtaster.score: 1.0
 ndex_chd.numhit: 2.0
 ndex.numhit: 4.0
 ndex_signor.numhit: 1.0
 prec.prec: 0.36264
 provean.score: -2.3
 pangalodb.sensitivity: 0.0
 pangalodb.specificity: 0.0112782
 phdsnpg.score: 0.93
 phastcons.phastcons100_vert: 1.0
 phastcons.phastcons470_mamm: 0.987
 phastcons.phastcons17way_primate: 0.961
 phylop.phylop100_vert: 4.239
 phylop.phylop470_mamm: 1.026
 phylop.phylop17_primate: 0.599
 polyphen2.hdiv_rank: 0.55554
 polyphen2.hvar_rank: 0.53365
 revel.score: 0.38
 rvis.rvis_evs: -0.41
 sift.score: 1.0
 sift.med: 2.74
 sift.seqs: 46.0
 segway.mean_score: 0.0858073982609
 siphy.logodds_rank: 0.62632
 spliceai.ds_ag: 0.0004
 spliceai.ds_al: 0.0
 spliceai.ds_dg: 0.0004
 spliceai.ds_dl: 0.0
 spliceai.dp_ag: -1.0
 spliceai.dp_al: 0.0
 spliceai.dp_dg: 0.0
 spliceai.dp_dl: 0.0
 varity_r.varity_r_loo: 0.3558284342288971
 varity_r.varity_er_loo: 0.29223165
 vest.score: 0.754
 dbscsnv.ada_score: 0.5035390098589105
 dbscsnv.rf_score: 0.516
 gnomad.af: 0.000116777782496
 gnomad_gene.oe_lof: 0.34946
 gnomad_gene.oe_mis: 0.88424
 gnomad_gene.oe_syn: 1.0119
 gnomad_gene.lof_z: 3.7638
 gnomad_gene.mis_z: 0.92308
 gnomad_gene.syn_z: -0.1187
 gnomad_gene.pLI: 7.8292e-05
 gnomad_gene.pRec: 0.30551
 gnomad_gene.pNull: 1.1292e-05
 gnomad3.af: 0.000167535
 phi.phi: 0.48298

consequence_cols:
 - 2kb_downstream_variant
 - 2kb_upstream_variant
 - 3_prime_UTR_variant
 - 5_prime_UTR_variant
 - NMD_transcript_variant
 - NSD_transcript
 - complex_substitution
 - exon_loss_variant
 - frameshift_elongation
 - frameshift_truncation
 - inframe_deletion
 - inframe_insertion
 - intron_variant
 - lnc_RNA
 - miRNA
 - misc_RNA
 - missense_variant
 - polymorphic_pseudogene
 - processed_transcript
 - rRNA
 - ribozyme
 - scaRNA
 - snRNA
 - snoRNA
 - splice_site_variant
 - start_lost
 - start_retained_variant
 - stop_gained
 - stop_lost
 - stop_retained_variant
 - synonymous_variant
 - transcript_ablation

filtered_cols:
 - transcript
 - gene
 - consequence
 - protein_hgvs
 - cdna_hgvs
 - chrom
 - pos
 - ref_base
 - alt_base
 - clingen.disease
 - clingen.classification
 - ncbigene.entrez
 - omim.omim_id
 - uniprot.acc
 - dbsnp.rsid
 - aloft.tolerant
 - aloft.recessive
 - aloft.dominant
 - cadd.phred
 - chasmplus.score
 - chasmplus.pval
 - civic.molecular_profile_score
 - cosmic.variant_count
 - cosmic_gene.occurrences
 - cscape.score
 - cancer_genome_interpreter.resistant
 - cancer_genome_interpreter.responsive
 - clinpred.score
 - dann.score
 - dann_coding.dann_coding_score
 - dgi.score
 - ess_gene.indispensability_score
 - exac_gene.exac_pli
 - exac_gene.exac_pnull
 - exac_gene.exac_del_score
 - exac_gene.exac_dup_score
 - exac_gene.exac_cnv_score
 - fathmm.fathmm_score
 - fathmm_xf_coding.fathmm_xf_coding_score
 - funseq2.score
 - gerp.gerp_rs
 - ghis.ghis
 - gwas_catalog.pval
 - genehancer.score
 - linsight.value
 - lrt.lrt_score
 - lrt.lrt_omega
 - loftool.loftool_score
 - mavedb.score
 - metalr.score
 - metasvm.score
 - mutpred1.mutpred_general_score
 - mutpred_indel.score
 - mutation_assessor.score
 - mutationtaster.score
 - ndex_chd.numhit
 - ndex.numhit
 - ndex_signor.numhit
 - prec.prec
 - provean.score
 - pangalodb.sensitivity
 - pangalodb.specificity
 - phdsnpg.score
 - phastcons.phastcons100_vert
 - phastcons.phastcons470_mamm
 - phastcons.phastcons17way_primate
 - phylop.phylop100_vert
 - phylop.phylop470_mamm
 - phylop.phylop17_primate
 - polyphen2.hdiv_rank
 - polyphen2.hvar_rank
 - revel.score
 - rvis.rvis_evs
 - sift.score
 - sift.med
 - sift.seqs
 - segway.mean_score
 - siphy.logodds_rank
 - spliceai.ds_ag
 - spliceai.ds_al
 - spliceai.ds_dg
 - spliceai.ds_dl
 - spliceai.dp_ag
 - spliceai.dp_al
 - spliceai.dp_dg
 - spliceai.dp_dl
 - varity_r.varity_r_loo
 - varity_r.varity_er_loo
 - vest.score
 - dbscsnv.ada_score
 - dbscsnv.rf_score
 - gnomad.af
 - gnomad_gene.oe_lof
 - gnomad_gene.oe_mis
 - gnomad_gene.oe_syn
 - gnomad_gene.lof_z
 - gnomad_gene.mis_z
 - gnomad_gene.syn_z
 - gnomad_gene.pLI
 - gnomad_gene.pRec
 - gnomad_gene.pNull
 - gnomad3.af
 - phi.phi
 - Adipose_Subcutaneous
 - Adipose_Visceral_Omentum
 - Adrenal_Gland
 - Artery_Aorta
 - Artery_Coronary
 - Artery_Tibial
 - Brain_Amygdala
 - Brain_Anterior_cingulate_cortex_BA24
 - Brain_Caudate_basal_ganglia
 - Brain_Cerebellar_Hemisphere
 - Brain_Cerebellum
 - Brain_Cortex
 - Brain_Frontal_Cortex_BA9
 - Brain_Hippocampus
 - Brain_Hypothalamus
 - Brain_Nucleus_accumbens_basal_ganglia
 - Brain_Putamen_basal_ganglia
 - Brain_Spinal_cord_cervical_c-1
 - Brain_Substantia_nigra
 - Breast_Mammary_Tissue
 - Cells_EBV-transformed_lymphocytes
 - Cells_Transformed_fibroblasts
 - Colon_Sigmoid
 - Colon_Transverse
 - Esophagus_Gastroesophageal_Junction
 - Esophagus_Mucosa
 - Esophagus_Muscularis
 - Heart_Atrial_Appendage
 - Heart_Left_Ventricle
 - Liver
 - Lung
 - Minor_Salivary_Gland
 - Muscle_Skeletal
 - Nerve_Tibial
 - Ovary
 - Pancreas
 - Pituitary
 - Prostate
 - Skin_Not_Sun_Exposed_Suprapubic
 - Skin_Sun_Exposed_Lower_leg
 - Small_Intestine_Terminal_Ileum
 - Spleen
 - Stomach
 - Testis
 - Thyroid
 - Uterus
 - Vagina
 - Whole_Blood
 - activator
 - adduct
 - agonist
 - allosteric modulator
 - antagonist
 - antibody
 - binder
 - blocker
 - chaperone
 - cofactor
 - inducer
 - inhibitor
 - ligand
 - modulator
 - negative modulator
 - positive modulator
 - potentiator
 - product of
 - stimulator
 - substrate
 - vaccine
 - AD
 - AR
 - AR
 - BG
 - Digenic
 - XL
 - 2kb_downstream_variant
 - 2kb_upstream_variant
 - 3_prime_UTR_variant
 - 5_prime_UTR_variant
 - NMD_transcript_variant
 - NSD_transcript
 - complex_substitution
 - exon_loss_variant
 - frameshift_elongation
 - frameshift_truncation
 - inframe_deletion
 - inframe_insertion
 - intron_variant
 - lnc_RNA
 - miRNA
 - misc_RNA
 - missense_variant
 - polymorphic_pseudogene
 - processed_transcript
 - rRNA
 - ribozyme
 - scaRNA
 - snRNA
 - snoRNA
 - splice_site_variant
 - start_lost
 - start_retained_variant
 - stop_gained
 - stop_lost
 - stop_retained_variant
 - synonymous_variant
 - transcript_ablation
 - LINE
 - LTR
 - Low_complexity
 - SINE
 - Satellite
 - Simple_repeat
 - Enhancer
 - Promoter
 - germline
 - somatic
 - Oncogene
 - TSG
 - fusion
 - coding_Yes
 - aloft.pred_Dominant
 - aloft.pred_Recessive
 - aloft.pred_Tolerant
 - aloft.conf_High
 - aloft.conf_Low
 - ccre_screen._group_CTCF-only
 - ccre_screen._group_DNase-H3K4me3
 - ccre_screen._group_PLS
 - ccre_screen._group_dELS
 - ccre_screen._group_pELS
 - ccre_screen.bound_Yes
 - ensembl_regulatory_build.region_CTCF_binding_site
 - ensembl_regulatory_build.region_TF_binding_site
 - ensembl_regulatory_build.region_enhancer
 - ensembl_regulatory_build.region_open_chromatin_region
 - ensembl_regulatory_build.region_promoter
 - ensembl_regulatory_build.region_promoter_flanking_region
 - exac_gene.exac_cnv_flag_N
 - exac_gene.exac_cnv_flag_Y
 - mutationtaster.prediction_Automatic Disease Causing
 - mutationtaster.prediction_Automatic Polymorphism
 - mutationtaster.prediction_Damaging
 - mutationtaster.prediction_Polymorphism
 - mutationtaster.model_complex_aae
 - mutationtaster.model_simple_aae
 - mutationtaster.model_without_aae
 - prec.stat_lof-tolerant
 - prec.stat_recessive
 - sift.confidence_High
 - sift.confidence_Low

Benchmark_cols:
 cadd.phred: 'CADD'
 cscape.score: "CSCAPE"
 clinpred.score: 'ClinPred'
 dann.score: 'DANN'
 dann_coding.dann_coding_score: 'DANN_Coding'
 dgi.score: 'DGI_score'
 fathmm_xf_coding.fathmm_xf_coding_score: 'FATHMM_coding'
 funseq2.score: 'Funseq2'
 linsight.value: 'Linsight'
 lrt.lrt_score: 'LRT'
 loftool.loftool_score: 'Loftool'
 metasvm.score: 'MetaSVM'
 metalr.score: 'MetaLR'
 mutpred1.mutpred_general_score: 'MutPred'
 mutpred_indel.score: 'MutPred_indel'
 mutation_assessor.score: 'Mutation_Assessor'
 mutationtaster.score: 'Mutation_Taster'
 provean.score: 'Provean'
 phdsnpg.score: 'PHDSNPG'
 revel.score: 'Revel'
 sift.score: 'SIFT'
 vest.score: 'VEST'
 dbscsnv.ada_score: 'dbSCSNV_ADA'
 dbscsnv.rf_score: 'dbSCSNV_RF'
 varity_r.varity_r_loo: 'varity_r'
 varity_r.varity_er_loo: 'varity_er'
